# Generated by Django 4.2.4 on 2023-10-01 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilePicture', models.ImageField(null=True, upload_to='', verbose_name='Profile Picture')),
                ('firstName', models.CharField(max_length=255, null=True, verbose_name='First Name')),
                ('lastName', models.CharField(max_length=255, null=True, verbose_name='Last Name')),
                ('dateOfBirth', models.DateField(null=True, verbose_name='Date of Birth')),
                ('age', models.IntegerField(default=0, null=True, verbose_name='Age of Alumni')),
                ('mobileNumber', models.CharField(max_length=13, null=True, verbose_name='Mobile Number')),
                ('emailID', models.EmailField(max_length=254, null=True, verbose_name='Email Address')),
                ('followers', models.ManyToManyField(blank=True, to='api.account')),
                ('following', models.ManyToManyField(blank=True, to='api.account')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
        migrations.AddField(
            model_name='post',
            name='caption',
            field=models.CharField(max_length=255, null=True, verbose_name='Caption'),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Likes'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[('Computer Science and Engineering', 'Computer Science and Engineering')], max_length=100, null=True, verbose_name='Branch')),
                ('section', models.CharField(choices=[('None', 'None'), ('Alpha', 'Alpha'), ('Beta', 'Beta'), ('Gamma', 'Gamma')], max_length=100, null=True, verbose_name='Section')),
                ('batch', models.CharField(max_length=100, null=True, verbose_name='Batch')),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.account')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startYear', models.CharField(max_length=4, null=True, verbose_name='Start Year')),
                ('department', models.CharField(choices=[('Computer Science and Engineering', 'Computer Science and Engineering')], max_length=100, null=True, verbose_name='Department')),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.account')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, null=True, verbose_name='Text')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('likes', models.IntegerField(default=0, verbose_name='Likes')),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.account')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.account'),
        ),
        migrations.AddField(
            model_name='post',
            name='followers',
            field=models.ManyToManyField(blank=True, to='api.comment'),
        ),
    ]
