# Generated by Django 4.2.4 on 2023-10-07 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_account_job_remove_post_text_post_caption_post_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='followers',
            new_name='comments',
        ),
    ]
