# Generated by Django 4.2.4 on 2023-11-09 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_post_likes_like_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='location',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.CharField(max_length=255, null=True, verbose_name='Role'),
        ),
    ]
